### ISSUE TITLE
Added Get Permutations and Serilog with File Sink

### ISSUE THREAD

**Issue by lukas-tr** [htl-perg-2019-20-5ahif/anagram-checker-exercise-lukas-tr#1]
I added *Serilog with File Sink* and *Get Permutations*

**Comment by rstropek** [comment]
Hi @lukas-tr!

Thank you for your solution. The two extra points are yours.

Two tips for further improvement for talented devs like you:

* I like that you used DI for command line, too. .NET Core 3 offers a special functionality for that: [Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host). It works similar to ASP.NET's former Web Host, but for command line tools and microservices that do not implement HTTP-based Web APIs.
* For command line parsing, consider the NuGet package [CommandLineParser](https://www.nuget.org/packages/CommandLineParser/). Works really well.

Greetings,
Rainer Stropek.
